DEF-2688 Added duration and start delay spread
defold/defold pull request #1550
Opened 2017-05-15 04:42 UTC by britzl

* Made inherit velocity into a curvable emitter property
* Also started using the spawn rate spread to calculate the spawn rate
of the emitter on creation
* Added new tests

2017-05-15 06:42 UTC, RagnarSvenssonKing requested changes
We also need editor2 implementation of properties etc.

2017-05-30 11:11 UTC, RagnarSvenssonKing requested changes

2017-06-08 12:39 UTC, RagnarSvenssonKing approved these changes

2017-06-09 07:20 UTC, ragnard-king reviewed
Two comments:

- `CurveSpread` with `curvable?` `false` feels a little weird to me as it's not really a curve, just a value and a spread. I understand piggybacking on the existing record is perhaps quicker/slightly less code, but wondering if that's worth it...
- should we have save/build tests with the new spread-properties set to non-default values?

2017-06-12 07:08 UTC, ragnard-king reviewed
Looks good, but still no tests for non-default values for the new params. Intentional?

2017-06-13 07:13 UTC, merged