Launcher update support
defold/defold pull request #1602
Opened 2017-05-31 13:36 UTC by chmu

2017-06-01 08:09 UTC, RagnarSvenssonKing requested changes

2017-06-01 13:18 UTC, erikangelin-king requested changes
I so want this feature! Some minor issues/questions left!

2017-06-15 08:00 UTC, erikangelin-king approved these changes

2017-06-28 08:46 UTC, matgis-king requested changes
Code looks good overall, but there are potential problems in `launcher.cpp` with obtaining the launcher path on Windows.

2017-09-06 09:18 UTC, matgis-king approved these changes

2017-09-06 10:26 UTC, merged