Unchanged files are saved because data stored in strings is not sanitized (DEFEDIT-1197)
defold/defold pull request #1871
Opened 2017-10-26 17:30 UTC by matgis-king

Includes but probably not limited to:
* The "load_dynamically" property on Factories.
* Vector properties since we now write spaces after comma separators.
2017-10-26 19:30:53 (Mats.Gisselson)
(LINK REMOVED)

2017-10-30 09:47 UTC, erikangelin-king requested changes
Looks nice but I get weird diffs in blossom blast :( May be unrelated!

2020-05-21 06:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/defold/defold?pullRequest=1871) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/defold/defold?pullRequest=1871) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/defold/defold?pullRequest=1871) it.</sub>

2020-06-28 11:42 UTC, matgis-king commented
@JCash I'm a bit afraid of this change, as I think it might impact project load times. That's why we initially held off on merging it. It's also the sort of thing you kind of want to test quite a lot before committing to it. Since it was created a while ago, I'm not certain the file formats remain exactly the same as well.

You could close it if you like. We could dig it up again and use it as a reference point in case we decide to go ahead with the change at a later point.

2023-04-18 09:54 UTC, Jhonnyg commented
This PR is has been stale for several years and is not likely to be worked on, closing!

2023-04-18 09:54 UTC, closed without merging