Defedit 1560 - Rebundle command
defold/defold pull request #2826
Opened 2019-02-20 11:18 UTC by markusgustavssonking

2019-02-20 15:09 UTC, vlaaad requested changes

2019-02-20 16:04 UTC, matgis-king requested changes
Reviewed. Great feature!

I did find an issue, though. If I delete the output directory, the Rebundle command will fail. It seems we currently call `(fs/create-directories! ...)` for the selected output directory from within the `::bundle-dialog/query-output-directory` handler. I think we need to move the call to the `app-view/bundle!` function now that this feature exists.

2019-02-21 17:58 UTC, vlaaad approved these changes
LGTM!

2019-02-22 09:25 UTC, matgis-king approved these changes

2019-02-22 09:51 UTC, merged