DEFEDIT-1677 Add toggle comment shortcut
defold/defold pull request #3054
Opened 2019-05-06 14:48 UTC by vlaaad

2019-05-07 10:00 UTC, markusgustavssonking reviewed
Seems to work fine but the colors are off on the line under the last commented line after toggle when editing a C file. Don't know if this is new or if it was like that already. static keyword is missing orange highlight.
![colors_wrong](https://user-images.githubusercontent.com/46451484/57291399-ad4bc800-70bf-11e9-95e6-5a9beb1607c5.PNG)

2019-05-07 10:31 UTC, matgis-king requested changes
Generally works well! Found some additional issues in addition to the review comments:
* Seems like this is causing some boxed math warnings.
* If I've selected a commented-out block but the selection contains empty lines, it will add an additional comment level instead of removing the comments.
* I think we should move the **Toggle Comment** menu item above **Reindent Lines** because the **Convert Indentation** item expands a submenu and it looks a bit weird to me for some reason.

2019-05-13 15:48 UTC, matgis-king approved these changes

2019-05-16 06:50 UTC, markusgustavssonking approved these changes
👍

2019-05-16 06:51 UTC, merged