Defedit 4103 new file and folder dialogs
defold/defold pull request #4141
Opened 2019-06-04 08:22 UTC by markusgustavssonking

Fixes #4103

2019-06-04 09:47 UTC, vlaaad requested changes
Code looks good to me, found few minor concerns. UI can be improved a bit:
1. Confirm button text in **New Folder** dialog should convey action, e.g. *Create Folder* instead of *Ok*
2. I don't like some aspects of **...** button in this dialog: ![Screenshot from 2019-06-04 11-31-18](https://user-images.githubusercontent.com/732554/58868312-57694080-86bc-11e9-8449-b7f70abfb0f8.png)
   - It should not have a bright border, this is for "main" dialog buttons, this one draws too much attention
   - there should either be a little bit of space between text input and button, or button should not have round corners
3. Preview text input should have `:editable false` instead of `:disable true`: that way it has clearer indication that this text is not editable. It will be selectable too, which is useless but nice I guess.

2019-06-04 09:54 UTC, matgis-king requested changes
Works great! There are a few small style tweaks I'd like to see before merging, though.

2019-06-05 09:45 UTC, vlaaad approved these changes

2019-06-05 15:31 UTC, matgis-king approved these changes

2019-06-05 15:42 UTC, merged