Specify exact JDK version to download
defold/defold pull request #4800
Opened 2020-05-20 03:17 UTC by subsoap

There are multiple versions of JDK 11 on https://jdk.java.net/archive/ which may be confusing, the editor uses jdk11.0.1

2020-05-20 03:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/defold/defold?pullRequest=4800) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/defold/defold?pullRequest=4800) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/defold/defold?pullRequest=4800) it.</sub>

2020-05-20 05:09 UTC, subsoap commented
I think the official archives of JDK don't get security patches anymore? not sure if that's an issue to use the old ones
https://adoptopenjdk.net/index.html?variant=openjdk11&jvmVariant=hotspot this version does have security patches but I think it had issues with bob in the past

2020-05-20 07:41 UTC, JCash commented on README_SETUP.md
> +You need Java JDK 11 installed to build the tools. [Download and install release 11.0.1 from OpenJDK](https://jdk.java.net/archive/). When Java is installed you may also add need to add java to your
We have actually specified it elsewhere, just not here, which is an oversight.

```
$ (cd ~/work/defold && rg "11\.0\.2")                                                                      09:39:58
editor/README_CURSIVE.md
31:3. Under the Project SDK section, choose Java version **11.0.2** from the dropdown. If that's not available from the dropdown, you'll need to tell IntelliJ where to find it. In that case you must browse for the JDK folder by clicking the **New...** button. Close the Project settings dialog when you're done.

editor/README.md
10:* Download the [macOS](https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_osx-x64_bin.tar.gz) version and extract it
11:* Run `sudo cp -R <path-to-extracted-folder>/jdk-11.0.2.jdk /Library/Java/JavaVirtualMachines/`
13:* Switch to the new version by running `/usr/libexec/java_home -v 11.0.2`
17:* Download [Linux](https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz) version and extract it somewhere
```

2020-05-20 07:43 UTC, JCash commented
As for bumping to newer Java versions, I'm not against it.
We chose 11, since that's what JavaFX needed when we updated.
Choosing a newer version _should_ be ok, but I'll refer to @vlaaad, @matgis-king, @bagucode for further info.

2020-05-20 07:44 UTC, JCash requested changes
It's actually 11.0.2

2020-05-20 08:22 UTC, matgis-king commented
@JCash Seems we missed some locations that still refer to `11.0.1`, for example `java_version = '11.0.1'` in `editor/scripts/bundle.py`, so it seems we still bundle `11.0.1` with the editor at least.

I think it makes sense to update the docs to say `11.0.2`, but we should do a pass and make sure we use it everywhere. Probably should be a separate PR, though.

There's a particular thing in the editor updater where we consider the embedded `jdk11.0.1` to be one of the `protected-dirs` that I'm unsure of. Not sure if we should edit that or add another entry to the `protected-dirs` list. Perhaps @vlaaad knows?

2020-05-20 08:34 UTC, vlaaad commented
Hmmm yeah, there were problems on windows with overwriting JVM files while JVM is running. As far as I remember (and looking at the updater code seems to confirm it), it is safe to update to new JDK as long as it's saved to a different folder in the Defold installation directory. See also: my [note about updating JDK version](https://github.com/defold/defold/blob/dev/editor/scripts/bundle.py#L31-L35) in the bundle script.

Another thing I just remembered: we store JDKs in our s3 bucket. Doing that required me to re-archive the windows version of JDK that is distributed as a `zip` file (as opposed to `tar.gz` for mac and linux).

Any 11+ JDK will work locally, but the editor is distributed with `11.0.1`.

2020-05-22 07:04 UTC, JCash approved these changes

2020-05-22 07:30 UTC, merged