Issue-2872-Fix-incidential-fullscreen-editor-exit-by-pressing-esc-key
defold/defold pull request #4888
Opened 2020-06-09 08:28 UTC by madwareru

Closes #2872

2020-06-09 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/defold/defold?pullRequest=4888) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/defold/defold?pullRequest=4888) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/defold/defold?pullRequest=4888) it.</sub>

2020-06-11 08:13 UTC, matgis-king requested changes
Great find! Thanks for finding a solution to this annoying problem!

However, I think we should move the call to `(.setFullScreenExitKeyCombination stage KeyCombination/NO_MATCH)` out to the `boot-open-project/load-stage` function, just before we call `app-view/restore-window-dimensions`.

Because we always want to prevent the Escape key from exiting full-screen, even if the editor was not started in full-screen mode.

2020-06-11 20:26 UTC, madwareru commented
Seems to be done :)

2020-06-12 06:51 UTC, matgis-king commented
Thanks for the fix! Merging!

2020-06-12 06:51 UTC, merged