issue-editor2-2700-options-to-move-gui-node-up-down-should-be-in-context-menu
defold/defold pull request #4941
Opened 2020-06-21 10:42 UTC by madwareru

Closes defold/editor2-issues#2700

Added context menu so gui nodes are possible to move up/down with a context menu and user faster figure out hotkey for it. Optional side effect: seems to affect atlas outline too so we can easily flip sprites in animation

2020-06-21 10:48 UTC, madwareru commented
@matgis-king please review this (somehow I'm not allowed to request your review other way)

2020-06-21 18:41 UTC, vlaaad requested changes
Hi @madwareru, thanks for your contribution!

I have a couple of concerns about these context menu items:
- I think they should not be at the very top of a context menu. I would expect more commonly used options to be there, while Move Up/Down commands are there mostly to teach a user that this ability exists. My gut feeling tells me it should be below the cut/copy/paste section. Or above. What do you guys think, @matgis-king @eangelin @bagucode?
- It would be nice if these options could be shown as disabled (aka visible, but greyed out) when the move is not possible — for example when the item is first or last in the list. This can be achieved by adding `(enabled? ...)` clause to command definition.

2020-06-21 19:57 UTC, madwareru commented
Thanks Vlad, I agree, position for these menu items requires some discussion, so I will wait what other reviewers say and then try to position it in appropriate place.

> It would be nice if these options could be shown as disabled (aka visible, but greyed out) when the move is not possible — for example when the item is first or last in the list. This can be achieved by adding `(enabled? ...)` clause to command definition.

Interesting. Seems like a handy feature.

2020-06-21 21:29 UTC, madwareru commented
I just updated PR to support `(enabled? ...)` feature.
Still waiting what other reviewers think about positioning of context menu items.

2020-08-03 11:17 UTC, vlaaad commented on editor/src/clj/editor/atlas.clj
> +                          (> node-child-index 0)))
Please use `(pos? x)` instead of `(> x 0)`

2020-08-03 11:17 UTC, vlaaad commented on editor/src/clj/editor/atlas.clj
> +                          (< node-child-index (- (.size children) 1))))
Please use `(dec x)` instead of `(- x 1)`

2020-08-04 11:55 UTC, madwareru commented
Thanks @vlaaad! Fixed :) But there are some strange trouble in CI. I'll try to make a fresh build and test it on my machine today

2020-08-04 12:51 UTC, britzl commented
I've restarted the CI job. Let's see if it is only a temporary hiccup (it has happened before with GitHub CI).

2020-08-08 18:18 UTC, vlaaad approved these changes
Tested it locally — works wonderfully!

Please update remaining uses of `(> x 0)` to `(pos? x)` and `(- x 1)` to `(dec x)`

2020-12-15 23:16 UTC, merged