fix: check end of stream of sound
defold/defold pull request #5290
Opened 2020-10-22 17:29 UTC by pathway27

Wondering if this is what's required for https://github.com/defold/defold/issues/5270 ?

2020-10-22 17:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/defold/defold?pullRequest=5290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/defold/defold?pullRequest=5290) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/defold/defold?pullRequest=5290) it.</sub>

2020-10-23 09:06 UTC, JCash requested changes

2020-10-23 09:06 UTC, JCash commented on engine/sound/src/sound.cpp
> +        return sound_instance->m_Playing && !sound_instance->m_EndOfStream;
Have you run the tests?
The first thing that happened is that it failed.

Also, when running the repro case with this fix, the app crashed.
Did you test your fix?

I don't know _why_ it was commented out, but never removed, but it's slightly more complicated than that. You need to read the code, test it, and reason about why your fix works (and put your reasoning in the PR)

2020-11-07 16:50 UTC, pathway27 commented
Sorry something came up, I will let someone else take over.

2020-11-07 16:50 UTC, closed without merging

2020-11-10 18:03 UTC, marcopar commented
looks like this is closed but not fixed?
shouldn't be opened again?

2020-11-10 21:23 UTC, britzl commented
@marcopar I think it's better if the PR remains closed. If someone else want to attempt a fix for #5270 they should open a new PR.

2020-11-10 21:49 UTC, marcopar commented
Oh sure... I thought this was the bug report.... 
:facepalm: