Extended logs for release version
defold/defold pull request #6007
Opened 2021-08-25 16:53 UTC by SalavatR

Hi! Sometimes we need logs in release version

I did it blindly because I can't build the engine

If I understood correctly, it will be enough to declare one of the options in the .appmanifest file
MIN_LEVEL_SEVERITY_DEBUG || MIN_LEVEL_SEVERITY_USER_DEBUG || MIN_LEVEL_SEVERITY_INFO || MIN_LEVEL_SEVERITY_WARNING || MIN_LEVEL_SEVERITY_ERROR || MIN_LEVEL_SEVERITY_FATAL 

And can we write native extention for SetCustomLogCallback?

2021-08-25 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/defold/defold?pullRequest=6007) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/defold/defold?pullRequest=6007) before we can accept your contribution.<br/><hr/>**Salavat Rakhmanov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/defold/defold?pullRequest=6007) it.</sub>

2021-08-30 07:47 UTC, JCash requested changes

2021-08-30 07:47 UTC, JCash commented on engine/dlib/src/dlib/log.cpp
> +static bool LogAvailable()
"IsLogAvailable()" is more in line with the current naming.

2021-08-30 07:47 UTC, JCash commented on engine/dlib/src/dlib/log.cpp
> +#if  MIN_LEVEL_SEVERITY_DEBUG || MIN_LEVEL_SEVERITY_USER_DEBUG || MIN_LEVEL_SEVERITY_INFO || MIN_LEVEL_SEVERITY_WARNING || MIN_LEVEL_SEVERITY_ERROR || MIN_LEVEL_SEVERITY_FATAL
Defold defines should be prefixed with "DM_"

Also, I think "MIN_LEVEL" is very non intuitive and not explaining which system they belong to.
Perhaps "DM_LOG_" is a good prefix.

Also, "MIN" implies that there is a "MAX", but there isn't one, so I think we should skip the "MIN" part.

2021-08-30 07:47 UTC, JCash commented on engine/dlib/src/dlib/log.cpp
> +    g_LogLevel = GetInitLogLevel();
This is the only real change in this PR, and I don't see a big difference here.

I think you need to explain your use case in further detail.

2021-08-30 07:48 UTC, JCash commented
What is your use case?

2021-09-02 07:47 UTC, SalavatR commented
> What is your use case?
> 
> What platform are you targeting?
> E.g. I believe Android and iOS don't want you to spam output in the log files.
> 
> Also, if you want to enable logging in release builds, the proper way would be to use
> 
> ```
> platforms:
>     common:
>         context:
>             excludeLibs: ["engine_release"]
>             libs: ["engine"]
> ```
> 
> However, when I tested it just now, it's not working correectly, since the server adds both "-lengine_release -lengine" and it will use the release version (with logging turned off).
> That to me is the real fix, to make the override system work as intended.

Hi!
I changed some logic and names
Ideas was:
 1) Enable logs in release, because sometimes release and debug versions work differently
 2) Use DM_LOG_SEVERITY_LEVEL_FROM_  to limit spam
 3) Use g_CustomLogCallback and g_CustomLogCallbackUserData to handle logs with any plugin(Sentry, gameanalitycs, etc)
 4) For testing release version use DM_SYSTEM_LOG_ENABLED to view logs in adb, browser console, etc
 
 If i cant use 
 common:
    context:
        defines: ["MIN_LEVEL_SEVERITY_ERROR"]
        
 Which system should i ovverride and where to initialize?
 
 P.S. sorry for my broken english

2021-10-05 10:05 UTC, JCash commented
> because sometimes release and debug versions work differently
In which sense do you mean?

Note that your changes aren't really solving your problem, since you've added the defines to the _engine_ code, and those libraries are statically build into libraries. These libraries are not rebuilt when you build using native extensions.

2021-11-22 10:37 UTC, closed without merging

2021-11-22 10:37 UTC, SalavatR commented
https://github.com/SalavatR/def_native_logger 
created extention for logs in release)