Issue-6048 Build time measurements and json/html report
defold/defold pull request #6582
Opened 2022-05-07 09:43 UTC by AGulev

Generates new build report that provides information about build time for each stage of the building process.
It uses the same `build-report` arguments for the bob.jar tool but adds `_time` postfix to the provided file name. 

Fix https://github.com/defold/defold/issues/6048

2022-05-07 10:12 UTC, AGulev commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TimeProfiler.java
> +    public static void addMark(String shortName, String fullName) {
This is a way to show a more on the flame chart, just a flag that something happened
like this:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/2209596/167249848-150c5619-cc82-468d-a9e7-93f28f52a4fd.png">

2022-05-07 10:12 UTC, AGulev commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TimeProfiler.java
> +        HashMap<String, Boolean> additionalBooleanData;
Json supports 3 variable types

2022-05-07 10:15 UTC, AGulev commented
Time repost example:
[build_rep_time.html.zip](https://github.com/defold/defold/files/8644883/build_rep_time.html.zip)

2022-05-10 12:01 UTC, AGulev commented
Current report example is available here https://agulev.com/html/time-report-example/time_report.html

2022-05-12 08:00 UTC, JCash requested changes
Looks good!
Only a small change request

2022-05-12 11:55 UTC, AGulev commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/AtlasBuilder.java
>          TextureSetResult result = AtlasUtil.generateTextureSet(project, task.input(0));
Done! Thx

2022-05-12 11:57 UTC, AGulev commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TimeProfiler.java
> +        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
Good point! I made some changes in code to prevent using of TimeProfiler methods when this thread has started

2022-05-12 13:45 UTC, JCash approved these changes

2022-05-12 13:51 UTC, merged