Tests for the gui.cancel_animation function incorrectly return a correct test result
defold/defold pull request #6591
Opened 2022-05-10 22:52 UTC by coderm4ster

In tests for gui.cancel_animation function, the transformation matrix contains invalid values (nan).

The following two functions are affected in the "engine/gui/src/test/test_gui_script.cpp" file:
- TestCancelAnimation
- TestCancelAnimationComponent

In both test functions, the SetSceneResolution function call is missing after Scene is created. As a result, after the RenderScene function is executed, the passed transformation matrix contains invalid values. Because of this, the test functions incorrectly returns a correct test result.

2022-05-13 09:58 UTC, JCash reviewed
Fix indentation

2022-05-13 09:59 UTC, JCash requested changes
Fix indentation

2022-05-13 20:23 UTC, coderm4ster commented
Ahh, sorry, indentation fixed

2022-05-16 07:49 UTC, JCash approved these changes

2022-05-30 13:35 UTC, merged