Issue 6529 constant buffers array
defold/defold pull request #6866
Opened 2022-08-10 12:47 UTC by Jhonnyg

2022-08-10 15:52 UTC, Jhonnyg commented on engine/render/src/render/constant.cpp
> +    memmove(p_current, p_next, remaining * sizeof(dmVMath::Vector4)); // if it's the last item, then "remaining" will be 0
I think this was a bug previously, memmove expects bytes and remaining is just number of items to move

2022-08-10 15:56 UTC, Jhonnyg commented on engine/render/src/render/render_private.h
> +    void SetNamedConstantAtIndex(HNamedConstantBuffer buffer, dmhash_t name_hash, dmVMath::Vector4 value, uint32_t value_index);
Move to DMSDK?

2022-08-10 15:58 UTC, Jhonnyg commented on engine/render/src/render/render_private.h
> +    void SetNamedConstantAtIndex(HNamedConstantBuffer buffer, dmhash_t name_hash, dmVMath::Vector4 value, uint32_t value_index);
Maybe also rename it to SetNamedConstantValueAtIndex or something, since it's used to set a value somewhere in a constant array 🤔

2022-08-10 17:02 UTC, Jhonnyg commented on engine/render/src/render/render_script.cpp
> +            }
Hmm, do we need to clear the array when the table is gc'd? I'm not 100% sure what happens when the userdata is gc'd

2022-08-30 09:11 UTC, JCash requested changes
Looks good overall.

The Lua part has some C++ memory lifetime issue that needs fixing.

2022-08-31 21:23 UTC, Jhonnyg commented on engine/render/src/render/render_script.cpp
> +        cb->m_ConstantBuffer = 0;
This was an oversight in the previous commits, I wonder if we have any script/engine test for constants 🤔 But now we should correctly free any data from the constant table

2022-08-31 21:25 UTC, Jhonnyg commented on engine/render/src/render/render_script.cpp
> +    };
We don't need a gc for this since we don't allocate any memory for the table elements

2022-09-01 09:23 UTC, merged