Change from darwin to macos in editor
defold/defold pull request #6913
Opened 2022-08-26 11:15 UTC by britzl

We've recently changed platform name from x86_64-darwin to x86_64-macos in bob and build scripts but not in the editor.

2022-08-26 11:18 UTC, JCash approved these changes, later dismissed
Thanks!

2022-08-26 11:19 UTC, JCash commented on editor/src/clj/editor/updater.clj
> +                          "macos" (io/file path "../../")
This is a part where I'd say that the editor doesn't need a copy of Platform.java

2022-08-26 11:21 UTC, JCash commented on editor/src/clj/editor/util.clj
> +  "Returns :win32, :macos or :linux"
I think this type of editor code shouldn't need a duplicate of the PLatform.java.
But that's for the future tasks...

2022-08-26 11:29 UTC, matgis requested changes
You need to either edit or delete the editor's copy of `editor/src/java/com/defold/editor/Platform.java` as well, right?

2022-08-26 11:32 UTC, matgis approved these changes, later dismissed
Oh, I didn't realize Mathias already changed it on `dev`. Carry on, I guess!

2022-08-26 13:17 UTC, britzl commented
> This is a part where I'd say that the editor doesn't need a copy of Platform.java

> You need to either edit or delete the editor's copy of editor/src/java/com/defold/editor/Platform.java as well, right?

I did not even notice this! I assumed it used Platform.java from bob!

2022-08-26 14:32 UTC, britzl commented
@JCash and @matgis I switched to use of Platform.java from bob instead of the old copy we had in the Editor

2022-08-30 10:09 UTC, matgis approved these changes
I think I've fixed the final editor issue. This should be good to merge now!

2022-08-30 14:07 UTC, merged