Show informative error message on cyclic resource dependencies
defold/defold pull request #7262
Opened 2023-01-09 22:06 UTC by britzl

Cyclic resource dependencies in the editor did not show a user friendly error message. The message did in fact seem to indicate an error with the editor rather than with the project structure. This change detect cyclic dependencies and shows a popup with an improved error message to clearly indicate the problem to the developer.

Fixes #4893 
Fixes #3919 
Fixes #6724

2023-01-09 22:06 UTC, britzl commented
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

2023-01-09 22:07 UTC, britzl commented on editor/src/clj/editor/app_view.clj
> +        resource-path (some? proj-path) proj-path "'unknown'"]
I'm always getting "unknown" here. Not sure if I have adapted the initial code snippet from @matgis correctly?

2023-01-10 08:57 UTC, matgis requested changes
I made some suggestions for changes. You'll need to test if this works, but I think it should resolve some issues at least. 😅

2023-01-10 08:57 UTC, matgis commented on editor/src/clj/internal/node.clj
> +                    {:cause "cycle-detected"
These kind of "comparable strings" that are typically used as an enum are preferably expressed as [keywords](https://clojure.org/reference/data_structures#Keywords). Keywords are readable as strings but their strings are interned in a shared storage and comparisons are extremely cheap as a result.
```suggestion
                    {:cause :cycle-detected
```

2023-01-10 08:57 UTC, matgis commented on editor/src/clj/internal/node.clj
> +                     :node-type-name (node-type-name node-id evaluation-context)
I don't think we need to add the `:node-type-name` here. We can get the node type from the `node-id` when we generate the error message in `get-cycle-detected-help-message` above.

2023-01-10 08:57 UTC, matgis commented on editor/src/clj/editor/app_view.clj
> +
We can resolve the node type keyword from the `node-id` and add some whitespace here to make it more readable. This also lets us remove the `node-type-name` argument.

```suggestion
    (case (g/node-type-kw basis node-id)
      :editor.collection/CollectionNode
      (format "This is caused by a two or more collections referenced in a loop from either collection proxies or collection factories. One of the involved resources is: %s." resource-path)

      :editor.game-object/GameObjectNode
      (format "This is caused by two or more game objects referenced in a loop from game object factories. One of the involved resources is: %s." resource-path)

      :editor.code.script/ScriptNode
      (format "This is caused by two or more Lua modules required in a loop. One of the involved resources is: %s." resource-path)

      (format "This is caused by two or more resources referenced in a loop. One of the involved resources is: %s." resource-path))))
```

2023-01-10 08:57 UTC, matgis commented on editor/src/clj/editor/app_view.clj
> +  [node-type-name node-id]
We don't really need the `node-type-name` as an argument here. See below.

```suggestion
  [node-id]
```

2023-01-10 08:57 UTC, matgis commented on editor/src/clj/editor/app_view.clj
> +                         :text (get-cycle-detected-help-message (-> e ex-data :node-type-name) (-> e ex-data :node-id))}}))
We don't need to supply the `node-type-name` here - we can resolve it from the `node-id`.

```suggestion
                         :text (get-cycle-detected-help-message (-> e ex-data :node-id))}}))
```

2023-01-10 21:37 UTC, britzl commented
![Screenshot 2023-01-10 at 22 36 28](https://user-images.githubusercontent.com/1300688/211667625-43f7f91e-c777-4934-bf85-1611215750f0.png)

2023-01-11 07:05 UTC, matgis approved these changes
Looks good to me!

2023-01-11 07:11 UTC, merged