Bob debugging doc
defold/defold pull request #7289
Opened 2023-01-18 13:41 UTC by otsakir

How to debug Bob using IntelliJ - doc

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

2023-01-18 16:12 UTC, britzl commented on com.dynamo.cr/com.dynamo.cr.bob/README.md
> +	* `Program arguments` - Command line arguments given when executing bob. For example, `--platform x86_64-linux distclean build --archive bundle --variant debug`. It really depends on what parts of B
functionallity -> functionality

2023-01-18 16:13 UTC, britzl requested changes
Looks good! Very useful. I found a typo and a format issue.

2023-01-19 11:09 UTC, otsakir commented on com.dynamo.cr/com.dynamo.cr.bob/README.md
> +	* `Program arguments` - Command line arguments given when executing bob. For example, `--platform x86_64-linux distclean build --archive bundle --variant debug`. It really depends on what parts of B
ok

2023-01-19 11:10 UTC, otsakir commented on com.dynamo.cr/com.dynamo.cr.bob/README.md
> +1. Start the IDE and on the initial welcome screen choose _Open_' project. Navigate to Bob's source directory `com.dynamo.cr/com.dynamo.cr.bob` inside Defold's source tree.
ok

2023-01-19 11:24 UTC, britzl approved these changes

2023-01-23 16:51 UTC, merged