Bugfix for using multiple rendertargets in WebGL2
defold/defold pull request #7465
Opened 2023-03-14 00:08 UTC by Jhonnyg

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

2023-04-03 07:34 UTC, Jhonnyg commented on engine/graphics/src/opengl/graphics_opengl.cpp
> +            }
This is a webgl caveat only, which is super annoying.. Maybe we should state that in the docs

2023-04-03 07:35 UTC, Jhonnyg commented on engine/graphics/src/opengl/graphics_opengl.cpp
> +    #endif
We could maybe set the PFN_glDrawBuffers ptr to glDrawBuffers for emscripten and skip this define

2023-04-11 09:09 UTC, JCash requested changes

2023-04-11 09:09 UTC, JCash commented on engine/graphics/src/opengl/graphics_opengl.cpp
> +        bool first_set       = false;
When is this boolean actually set?

2023-04-11 16:40 UTC, merged