Upload Defold SDK and reference documentation to GitHub on release
defold/defold pull request #7538
Opened 2023-04-03 06:12 UTC by britzl

This change will upload the defoldsdk.zip and ref-doc.zip to GitHub on every release of Defold.

Fixes #7518

2023-04-03 08:04 UTC, JCash requested changes

2023-04-03 09:25 UTC, britzl commented on build_tools/release_to_github.py
> +        return os.path.basename(path) in ('bob.jar', 'defoldsdk.zip', 'ref-doc.zip') or is_editor_file(path)
Let me check again. The idea was to upload the big one.

2023-04-03 11:04 UTC, britzl commented on build_tools/release_to_github.py
> +        return os.path.basename(path) in ('bob.jar', 'defoldsdk.zip', 'ref-doc.zip') or is_editor_file(path)
Yep, nope, it's including the platform specific ones as well. I think it is ok if we only include the main one right?

2023-04-05 07:03 UTC, JCash commented on build_tools/release_to_github.py
> +        return os.path.basename(path) in ('bob.jar', 'defoldsdk.zip', 'ref-doc.zip') or is_editor_file(path)
Yeah, we rarely have any use of the platform specific ones.

2023-04-05 07:03 UTC, JCash approved these changes

2023-04-05 08:37 UTC, merged