Allow install/launch on iOS using ios-deploy
defold/defold pull request #7711
Opened 2023-06-01 09:51 UTC by vlaaad

Technical notes: I moved some stuff from `editor.adb` ns to `editor.fs` ns (`existing-path` check and `evaluate-path` helper).

User-facing changes: this changeset enhances the editor with functionality to install and launch bundled iOS applications on a connected iOS device. You need [ios-deploy](https://github.com/ios-control/ios-deploy) installed for this feature to work.

Fixes #5392

2023-06-01 14:01 UTC, matgis requested changes
Do we want to perhaps rename some things before merging?

2023-06-01 14:19 UTC, vlaaad commented on editor/src/clj/editor/bundle_dialog.clj
> +    (ui/value! ios-deploy-launch-check-box (prefs/get-prefs prefs "bundle-ios-ios-deploy-launch" false))))
Everything except `?` as a suffix for booleans makes sense. As [I've said before](https://vlaaad.github.io/2019-03-30/question-marks-in-clojure), `?` should be used as a suffix only for predicate functions, not for keywords that identify booleans. Maybe it's time to strip the `?` from the other `?`-suffixed settings?

2023-06-01 16:59 UTC, matgis commented on editor/src/clj/editor/bundle_dialog.clj
> +    (ui/value! ios-deploy-launch-check-box (prefs/get-prefs prefs "bundle-ios-ios-deploy-launch" false))))
I agree with your take on reserving `?` for predicate functions, but here we're talking about string keys in the preference store, so I don't think it necessarily applies here.

2023-06-05 08:52 UTC, matgis approved these changes
LGTM!

2023-06-05 09:10 UTC, merged