Show model's Vertex Count in profiler for models in Local Vector Space
defold/defold pull request #7748
Opened 2023-06-16 13:20 UTC by AGulev

Fix issue when models with Vector Space `Local` in its material aren't taken into account by the profiler.

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

2023-06-16 13:30 UTC, JCash approved these changes

2023-06-16 13:39 UTC, JCash requested changes
The count is now currently a mix of indices and vertices.

2023-06-16 13:39 UTC, JCash commented on engine/gamesys/src/gamesys/components/comp_model.cpp
> +            DM_PROPERTY_ADD_U32(rmtp_ModelVertexSize, ro.m_VertexCount * sizeof(dmRig::RigModelVertex));
Btw, number of indices isn't the same as number of vertices.
For vertices, it's `buffers->m_VertexCount`.
If you wish to include indices, you can do that ofc. see res_model.cpp for info about how these are set.

2023-06-16 15:25 UTC, AGulev commented on engine/gamesys/src/gamesys/components/comp_model.cpp
> +            DM_PROPERTY_ADD_U32(rmtp_ModelVertexSize, ro.m_VertexCount * sizeof(dmRig::RigModelVertex));
thx. fixed

2023-06-17 09:11 UTC, JCash approved these changes

2023-06-17 09:28 UTC, merged