Add `New window` option in Dock/TaskBar
defold/defold pull request #7828
Opened 2023-07-24 07:23 UTC by AGulev

New option `New window` for task bar menu added. It opens a new instance of the editor.

Fix https://github.com/defold/defold/issues/4863

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

2023-07-24 07:24 UTC, AGulev commented on editor/src/java/com/defold/editor/Start.java
> +        }
<img width="824" alt="Screenshot 2023-07-24 at 09 18 35" src="https://github.com/defold/defold/assets/2209596/4d8ab7b7-11e0-40af-9f4d-6ba36e96b186">

2023-07-24 07:24 UTC, AGulev commented on editor/src/java/com/defold/editor/Start.java
> +            logger.error("There was a security exception for: 'desktop.setAboutHandler'", e);
we have logger here. I missed it.

2023-07-24 07:25 UTC, AGulev commented on editor/src/clj/editor/app_view.clj
> +; please, change it there as well.
I would prefer to reuse java code in Clojure. But I think it's not something we want most of the time. So I just added this comment here to make sure we keep it sync.

2023-07-24 13:24 UTC, AGulev commented
Tested on win/mac/linux

2023-07-24 13:26 UTC, britzl approved these changes

2023-07-25 12:42 UTC, JCash commented
Do we have race condition for resources between the instances?
E.g.:
1) Opening the same project twice
2) "Global" files such as settings etc.
3) Are editor scripts affected?

2023-07-25 12:44 UTC, AGulev commented
@JCash I don't know, but we already can create a new project from `File->Open Project...`

2023-07-25 12:46 UTC, JCash commented
Ok, waiting for the first issue then :) 🤷

2023-07-25 12:58 UTC, AGulev commented
> Ok, waiting for the first issue then :) 🤷

I expect these things were investigated when the initial functionality was implemented.
I think adding one more place for doing the same, users can already do from another place for a couple of months shouldn't affect anything. But I'll wait for review from somebody from the editor team.

2024-02-05 12:30 UTC, matgis requested changes
Unless there is some reason for needing to do this before we do anything else, I think we should move the code that adds the context menu item into `boot-open-project/load-stage!` where we do the rest of the Window and Menu setup. That also makes it easy to invoke the existing Clojure code.

2024-02-05 12:30 UTC, matgis commented on editor/src/java/com/defold/editor/Start.java
> +                MenuItem dockMenuItem = new MenuItem("New window");
I think it should be "New Window", with a capitalized "W", to match the capitalization of the other entries in the menu?

2024-02-05 12:30 UTC, matgis commented on editor/src/java/com/defold/editor/Start.java
> +            logger.error("The OS does not support taskbar menu", e);
Can this even happen after the checks we do? If so, it should probably be logged as info, not an error.

2024-02-05 12:30 UTC, matgis commented on editor/src/java/com/defold/editor/Start.java
> +                            newWindow();
We shouldn't re-implement the functionality in Java, rather, we should either invoke the handler directly (although I can't find a convenient way to do that? I think is should be done how we do it from `editor.keymap/execute-command`).

Or we could break out the code in the `:open-project` `defhandler` into a Clojure function that we place next to the handler and call the Clojure function from here. Although to be honest I don't see why this code has to be in Java at all. Couldn't we do this from `boot-open-project/load-stage!` where we do all the other Window and Menu setup?

2024-02-05 12:34 UTC, closed without merging