TestFrustumOBB for model do not skip near_far
defold/defold pull request #7953
Opened 2023-09-04 17:59 UTC by d954mas

Fixed model frustum culling skipped near_far

Fixes https://github.com/defold/defold/issues/7952
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

2023-09-05 10:04 UTC, JCash requested changes

2023-09-05 11:17 UTC, britzl commented on engine/gamesys/src/gamesys/components/comp_model.cpp
> +            bool intersect = dmIntersection::TestFrustumOBB(frustum, render_item->m_World, render_item->m_AabbMin, render_item->m_AabbMax, false);
From a render script point of view something like this?

```lua
render.draw(model_pred, { frustum = frustum, skip_near_far = true })
```

2023-09-05 12:13 UTC, d954mas commented on engine/gamesys/src/gamesys/components/comp_model.cpp
> +            bool intersect = dmIntersection::TestFrustumOBB(frustum, render_item->m_World, render_item->m_AabbMin, render_item->m_AabbMax, false);
> This was a deliberate choice, as the number of extra culled objects are few in relation to the sides.

Thanks for answer. It is interesting that for meshes you use "false" but for model "true"

2023-09-05 12:21 UTC, d954mas commented
I make a feature request  to add frustum_skip_near_far.
```lua
render.draw(model_pred, { frustum = frustum, frustum_skip_near_far = true })
```
https://github.com/defold/defold/issues/7959

2023-09-06 09:07 UTC, JCash commented
Superceded by this PR: https://github.com/defold/defold/pull/7967

2023-09-06 09:07 UTC, closed without merging