Add documentation popup for code completions
defold/defold pull request #8048
Opened 2023-09-26 13:52 UTC by vlaaad

User-facing changes:

The code editor will now show a documentation popup for code completions if you press <kbd>Ctrl Space</kbd> again when the completion popup is already shown. The documentation popup shows the same information in the [Defold reference](https://defold.com/ref/stable/go/): descriptions, parameters, returns, and examples. It renders markdown, which will help integrate LSP completions that usually present the documentation using markdown formatting.

https://github.com/defold/defold/assets/732554/21ed7fe4-3d04-4a64-a648-0f4f78260e1b

Technical notes:

I ported the completion popup to cljfx. I also tidied up the positioning and sizing of the completion and documentation popups. The viewer is implemented as Defold-flavored HTML rendered as VBoxes of TextFlows, where Markdown is transformed into HTML. Took me a while to get right :D

Related to #7699

2023-09-26 13:55 UTC, AGulev commented
>The code editor will now show a documentation popup for code completions if you press Ctrl Space again when the completion popup is already shown. 

Could you pls add it into the editor manual in our `doc` repo? Also, it would be nice to make an announcement on the forum.

2023-09-27 15:53 UTC, matgis requested changes
Works great! The markdown mangling looks like it could have been painful. 😅

I found some reflection warnings and one place where I'm concerned about a `g/with-auto-evaluation-context` block lifetime.

2023-09-27 15:53 UTC, matgis commented on editor/src/clj/editor/markdown.clj
> +                        ;; e.g. type "vmath", then type "."
Style: The indentation of this comment looks a bit off?

2023-09-28 07:15 UTC, vlaaad commented on editor/src/clj/editor/code/view.clj
> +                                          ^double (reduce max 0.0)
Yes!

2023-09-28 07:21 UTC, vlaaad commented on editor/src/clj/editor/code/view.clj
> +           [javafx.stage PopupWindow Screen Stage]))
yes!

2023-09-28 08:16 UTC, merged