Add a local storage of uniform constants values to the OpenGL renderer
defold/defold pull request #8167
Opened 2023-10-20 18:02 UTC by aglitchman

This PR adds a local storage of uniform constant values to the OpenGL renderer. The point is not to send the same constants unless they differ between draw calls.

Fixes #8166 

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

2023-10-20 18:19 UTC, aglitchman commented
Test project - https://github.com/aglitchman/defold-drawcalls-test
It contains a simple scene with 50 models + 50 sprites + 1 label = 101 draw call per frame.

Before PR: 2994 calls.
After PR: 2643 calls.

What is optimized is shown in the following pseudo-code from RenderDoc. I got it from the test project, and it's a single draw call of the 3d model. I pointed the optimized stuff with the commented lines:
```c++
glUseProgram(Program 112)                                                         
glUniform4fv(Program 112, { 1.00, 1.00, 1.00, 1.00 })                             
glUniformMatrix4fv(Program 112, False, float[16])                                 
glUniformMatrix4fv(Program 112, False, float[16])                                 
// glUniformMatrix4fv(Program 112, False, float[16])                              
// glUniformMatrix4fv(Program 112, False, float[16])                              
// glUniform4fv(Program 112, { 1.00, 1.00, 1.00, 1.00 })                          
// glUniform4fv(Program 112, { 1.00, 1.00, 1.00, 1.00 })                          
glActiveTexture(GL_TEXTURE0)                                                      
glBindTexture(GL_TEXTURE_2D, Texture 113)                                         
glTexParameteri(Texture 113, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_NEAREST)     
glTexParameteri(Texture 113, GL_TEXTURE_MAG_FILTER, GL_LINEAR)                    
glTexParameteri(Texture 113, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE)                 
glTexParameteri(Texture 113, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE)                 
glUniform1i(Program 112, { 0 })                                                   
glTexParameteri(Texture 113, GL_TEXTURE_MIN_FILTER, GL_LINEAR)                    
glTexParameteri(Texture 113, GL_TEXTURE_MAG_FILTER, GL_LINEAR)                    
glTexParameteri(Texture 113, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE)                 
glTexParameteri(Texture 113, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE)                 
glBindBuffer(GL_ARRAY_BUFFER, Buffer 108)                                         
glEnableVertexAttribArray(Vertex Array 68, 0)                                     
glVertexAttribPointer(Vertex Array 68, Buffer 108, 0, 3, GL_FLOAT, False, 68, 0)  
glEnableVertexAttribArray(Vertex Array 68, 2)                                     
glVertexAttribPointer(Vertex Array 68, Buffer 108, 2, 3, GL_FLOAT, False, 68, 12) 
glEnableVertexAttribArray(Vertex Array 68, 1)                                     
glVertexAttribPointer(Vertex Array 68, Buffer 108, 1, 2, GL_FLOAT, False, 68, 52) 
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, Buffer 109)                                 
glDrawElements(6)                                                                 
glDisableVertexAttribArray(Vertex Array 68, 0)                                    
glDisableVertexAttribArray(Vertex Array 68, 2)                                    
glDisableVertexAttribArray(Vertex Array 68, 1)                                    
glBindBuffer(GL_ARRAY_BUFFER, No Resource)                                        
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, No Resource)                                
glActiveTexture(GL_TEXTURE0)                                                      
glBindTexture(GL_TEXTURE_2D, No Resource)                                         
```

Is it worth it? In fact, it would be great to measure performance. But how? Via ARB_timer_query?..

2023-10-20 18:51 UTC, AGulev commented
xcode open gl profiler (a separate tool) and trace function was pretty nice for it, but it seems like it's fully broken since I used it for the last time.
https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGLProfilerUserGuide/GettedStarted/GettingStarted.html#//apple_ref/doc/uid/TP40006475-CH20-SW1

2023-10-21 08:01 UTC, JCash requested changes
Generally good, but left some feedback for minor changes.

2023-10-24 22:40 UTC, aglitchman commented
@JCash Thanks for the comments! I'll take everything into consideration and rework it. But first I will test the rationale of this PR. I mean I need to see through apitrace or some similar app that the rendering time is reduced. Then I will finish the PR or cancel it.

PS Unfortunately, I won't have time to do benchmarks and to finish the PR before the end of Hacktoberfest (my free time ran out), but that's okay.

2023-10-25 11:15 UTC, aglitchman commented on engine/graphics/src/opengl/graphics_opengl.cpp
> +        dmArray<OpenGLConstantValue>& values = program->m_ConstantValues;
> I wonder if a simple hash32 would suffice?

I thought about that, but hash functions have a small chance of giving the same values, right? It seems to me that users can be paranoid about this. So I'll have to make an option in game.project like "optimize uniform constants". So you can toggle it on and off if you are in doubt.

2023-12-20 07:25 UTC, britzl commented
> PS Unfortunately, I won't have time to do benchmarks and to finish the PR before the end of Hacktoberfest (my free time ran out), but that's okay.

@aglitchman have you had a chance to work on this?

2023-12-24 21:42 UTC, aglitchman commented
> @aglitchman have you had a chance to work on this?

Sadly, not yet 🙌

2024-08-13 14:48 UTC, Jhonnyg commented
We cache uniform buffers now and apply them only when dirty, so I'm closing this one :) thanks anyway!

2024-08-13 14:48 UTC, closed without merging