Add multi texture support for sprites
defold/defold pull request #8183
Opened 2023-10-27 08:16 UTC by JCash

This feature lets you assigne multiple atlases to a sprite, enabling you to do effects like normal mapping etc.

By adding multiple `texcoord` vertex attributes to your material, and also adding multiple texture samplers, you will enable this feature for the sprites using your material.

Fixes https://github.com/defold/defold/issues/3233

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [x] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

2023-10-27 09:10 UTC, JCash commented on engine/gamesys/src/gamesys/resources/res_textureset.cpp
> +        }
I prefer early out

2023-10-27 09:10 UTC, JCash commented on engine/gamesys/src/gamesys/resources/res_textureset.cpp
> +        }
This part is new. We keep a lookup table from animation name (E.g. "foo" from "path/foo.png") into the frame index.
This allows us to lookup images between atlases.

2023-10-27 09:10 UTC, JCash commented on engine/graphics/src/vulkan/graphics_vulkan.cpp
> +        dmHashUpdateBuffer32(state, vertex_declaration->m_Streams, sizeof(VertexDeclaration::Stream) * vertex_declaration->m_StreamCount);
No need to loop over each stream+attribute.

2023-10-27 09:10 UTC, JCash commented on scripts/unpack_ddf.py
> +proto_type_to_string_map[google.protobuf.descriptor.FieldDescriptor.TYPE_BOOL]    = 'TYPE_BOOL'
Add support for enums...

2023-10-27 09:10 UTC, JCash commented on scripts/unpack_ddf.py
> +        print(descriptor.name, ":", e.name, get_descriptor_type(descriptor))
.. and properly getting the correct value.

2023-10-30 07:45 UTC, matgis commented on engine/gamesys/proto/gamesys/atlas_ddf.proto
> +// Editor format. Engine format is iun texture_set_ddf.proto
Typo: `iun`

2023-11-13 12:24 UTC, matgis requested changes
Editor & file format changes look good!

However, I think something might have broken when bundling with Bob. I get this error when I try to bundle a fresh project created from the Side Scroller Tutorial template:
```
/game.project
	File /Users/mats/Defold/Side scroller tutorial2/build/default/background/background.atlas does not exists
```

2023-11-20 13:49 UTC, Jhonnyg approved these changes, later dismissed
LGTM

2023-11-20 13:49 UTC, Jhonnyg commented on engine/gamesys/src/gamesys/components/comp_sprite.cpp
>      }
Maybe this should be a first class function in dmarray, we use this pattern alot afaik

2023-11-24 07:58 UTC, merged