Merge custom overrides representation
defold/defold pull request #8385
Opened 2024-01-10 11:42 UTC by Jhonnyg

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

2024-01-10 14:37 UTC, matgis requested changes
Nice job with using consistent terms everywhere! It's getting there.

I found some inefficiencies and things that could be improved, and I really think we need to `:cache` the `save-value` output after this change.

2024-01-10 14:37 UTC, matgis commented on editor/src/clj/editor/graphics.clj
> +              (keep (fn [attribute]
We can use destructuring on the argument here to make things clearer:
```clj
(fn [[name-key attribute-info]]
  ,,,)
```

2024-01-10 14:37 UTC, matgis commented on editor/src/clj/editor/model.clj
> +  (output save-value g/Any produce-save-value)
I think we should add `:cached` on this `output` since it does quite a lot of work now?

2024-01-10 14:55 UTC, Jhonnyg commented on editor/src/clj/editor/graphics.clj
> +        override:value-keyword (or attribute-value-keyword (:value-keyword override-info))
Not sure I follow, are you talking about the (:name-key attribute) ? I need to get the already stored data and only overwrite it if we have valid data, so I need the name-key from the incoming attribute

2024-01-10 15:05 UTC, matgis commented on editor/src/clj/editor/graphics.clj
> +        override:value-keyword (or attribute-value-keyword (:value-keyword override-info))
I mean `override:value-keyword` is an unconventional name for a let-binding.

2024-01-11 08:51 UTC, Jhonnyg commented on editor/src/clj/editor/graphics.clj
> +        override:value-keyword (or attribute-value-keyword (:value-keyword override-info))
Screw convention, I like to stick it to the man in very small ways! (it was a typo)

2024-01-11 08:54 UTC, Jhonnyg commented on editor/src/clj/editor/graphics.clj
> +(defn vertex-attribute-overrides->save-values [material-attribute-infos vertex-attribute-overrides]
Sure! I did the same for vertex-attribute-overrides->build-target

2024-01-11 11:24 UTC, merged