Fix issues with `physics.set_shape()` when `Allow Dynamic Transforms` is on
defold/defold pull request #8547
Opened 2024-02-15 13:59 UTC by AGulev

Fix issues with `physics.set_shape()` which appears when `Allow Dynamic Transforms` option in `game.project` is on.

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

2024-02-15 14:17 UTC, AGulev commented on engine/physics/src/physics/physics_2d.cpp
> +        shape->m_creationScale = radius;
Make sure we update `m_creationScale` (which is Defold specific modification of box2d) which used as a basic radius value for a  scale applying

2024-02-15 14:17 UTC, AGulev commented on engine/physics/src/physics/physics_2d.cpp
> +                polygon_shape->m_verticesOriginal[i] = polygon_shape->m_vertices[i];
synchronize originals with the verticsies to make sure we can apply scale

2024-02-21 14:45 UTC, Jhonnyg requested changes
Looks good! I think we can improve the error handling a bit, and perhaps add a test?

2024-02-21 14:45 UTC, Jhonnyg commented on engine/gamesys/src/gamesys/scripts/script_physics.cpp
> +        if (value == 0.0f)
I think you typically want to compare with an epsilon when comparing floats, there is no guarantee it is exactly 0.0f

2024-02-21 14:45 UTC, Jhonnyg commented on engine/gamesys/src/gamesys/scripts/script_physics.cpp
> +            luaL_error(L,"Shape size can't be 0");
Hm, this is just checking a float and doesn't say anything about the actual shape, I would probably make the function take a shape info as an argument, and rename it to CheckShape or something (the script library usually names functions Checkxxx where xxx is the type). Something like this perhaps? (pseudo-code)

```
void CheckShape(ShapeInfo info)
{
#define check_val(type_str, v) \
	if (fabs(v) < epsilon) \
		lua_error("%s ");

	switch(info.type)
	{
	case box:
		check_val("box.x", info.boxdimensions[0]);
		check_val("box.y", info.boxdimensions[1]);
		break;
	case sphere:
		check_val("sphere.radius", info.radius);
		break;
	etc..
	}
#undef check_val
}
```

2024-02-21 18:06 UTC, AGulev commented
@Jhonnyg I didn't add new function since for now this is the only place we use it, but I use marco with better error message like:
```
ERROR:SCRIPT: [string "src/gamesys/test/collision_object/get_set_err..."]:34: Shape 'shape_sphere_1' has invalid size '0' for 'diameter'
stack traceback:
  [C]:-1: in function set_shape
  [string "src/gamesys/test/collision_object/get_set_err..."]:34: in function <[string "src/gamesys/test/collision_object/get_set_err..."]:32>
  ```
  
  Also, I added a test

2024-02-21 19:26 UTC, Jhonnyg approved these changes

2024-02-21 19:27 UTC, merged