Set custom vertex data API
defold/defold pull request #8562
Opened 2024-02-19 15:31 UTC by Jhonnyg

2024-02-21 20:12 UTC, Jhonnyg commented on engine/gamesys/src/gamesys/gamesys_private.cpp
> +    int32_t FindMaterialAttributeIndex(const DynamicAttributeInfo& info, dmhash_t name_hash)
Hm, should perhaps be called something with dynamic

2024-02-21 20:15 UTC, Jhonnyg commented on engine/gamesys/src/gamesys/gamesys_private.cpp
> +                case 2: return dmGameObject::PropertyVar(dmVMath::Vector3(values[0], values[1], 0.0f));
We don't have a vector2

2024-02-21 20:19 UTC, Jhonnyg commented on engine/gamesys/src/gamesys/gamesys_private.cpp
> +                }
we add the indices backwards since we grab new indices from the back

2024-02-22 09:49 UTC, JCash requested changes
looks good, but could use some simplifications I believe.
In particular the reimplementing of the pool and dynamic array functionalities

2024-02-22 10:05 UTC, Jhonnyg commented on engine/gamesys/src/gamesys/components/comp_sprite.cpp
> +    static void FillSpriteAttributeInfos(const SpriteWorld* sprite_world, const SpriteComponent* component, SpriteAttributeInfo* material_infos, SpriteAttributeInfo* sprite_infos)
Yes, I think we can merge all the "attribute info" structs into a single one that lives in a graphics header or something. Particle generation is not part of gamesys and built before as a dependency to gamesys, so we need it further up in the chain. But I feel like that merge needs its own PR, I'll take a look

2024-02-22 19:48 UTC, merged