Increased editor UI contrast
defold/defold pull request #8855
Opened 2024-04-25 22:55 UTC by britzl

The editor color palette has been reverted back to what it looked like a few years ago with a higher contrast between text and other ui elements and the background.

Fixes #8384

LEFT = CURRENT LOW CONTRAST PALETTE, RIGHT = HIGH CONTRAST ORIGINAL PALETTE
<img width="1512" alt="Screenshot 2024-04-26 at 00 55 13" src="https://github.com/defold/defold/assets/1300688/9a01428f-75f3-4221-8172-2c085f154172">

<img width="1512" alt="Screenshot 2024-04-26 at 00 45 23" src="https://github.com/defold/defold/assets/1300688/43eb6064-10d3-4682-ac66-cdb00ebd2943">

<img width="1512" alt="Screenshot 2024-04-26 at 00 44 19" src="https://github.com/defold/defold/assets/1300688/bc1ba27e-aaeb-482b-bbca-1afb00a4efa6">

<img width="1512" alt="Screenshot 2024-04-26 at 00 43 43" src="https://github.com/defold/defold/assets/1300688/e243886e-bedc-433b-be1f-bf0d320fb28c">

<img width="1512" alt="Screenshot 2024-04-26 at 00 46 05" src="https://github.com/defold/defold/assets/1300688/223d4106-f0df-408a-bbf0-8cc44cf895ca">

2024-04-26 09:58 UTC, AGulev commented
@britzl could you pls rebase? Because now PR contains unrelated files

2024-04-26 13:55 UTC, britzl commented
> @britzl could you pls rebase? Because now PR contains unrelated files

Oh, thanks, missed that! Now merging to editor-dev.

2024-04-26 15:58 UTC, AGulev commented
Is it really higher contrast than it was? 
I mean it's become a bit blue, yes, but what contrast is the same, I think
Left is my experement (I think it's too much, yes). Right is how it was. In the middle it is your variant:
![image](https://github.com/defold/defold/assets/2209596/9bebf821-e85b-4982-b15e-d43328dca1fd)

2024-04-26 16:00 UTC, AGulev commented
UPD: when I look at it - yes, it is brighter. It doesn't feel like that from the first view because background is different as well.

2024-04-27 09:49 UTC, AGulev approved these changes
It's hard to say if it's better without using it. It's different and feels unusual because of the fact I get used to having old colors. From the first view, the text doesn't feel brighter.

We should decide if we should just change it or think about having two different themes with a switcher if it's possible, which adds an ability to add light to them in the future.  

I approve this PR, but I think you should decide with Mats if we should ship it.

2024-04-28 14:08 UTC, britzl commented
The difference between what we have now and my revert back to the old color values is subtle, but there is a difference for sure. The contrast is increased between the background and components (buttons, input fields, sliders etc). Perhaps the contrast can be increased further, perhaps by 10-20% or so.

2024-04-29 08:53 UTC, matgis requested changes
Wow, that's a lot of changes to the scss files. 😬

Just looking at the visual changes, I'd say there are some things that are better, some that made things worse, and some that are messed up.

* There is more contrast in editable fields, due to the higher text intensity and darker field backgrounds. However, the field labels now appear to have slightly less contrast against the background. Combined with the higher contrast field values, the labels are further diminished against the background due to their proximity to a higher-contrast element. I'm not sure if I find the end result to be less or more readable. I'm torn if I think we should make this change. 🤔
* The increased intensity of the text on highlighted and hovered items in the Assets and Outline panels, as well as the editor tabs and context menus is a clear improvement to me. I think we should do it.
* In form views, the intensity of text and field backgrounds is now more inconsistent than it was before. It was not fully consistent before either, but now there is a more pronounced difference between the field backgrounds of text fields, drop-down and table views in that both the backgrounds and the text intensities can have various values. I think we should make it consistent if we want to to make this change. I find the overall impression of editing a material slightly "messier" visually now.
* ⚠️ The section dividers in context menus straight up disappeared with this change. We need them back!
* ⚠️ The floating toolbar in scene views became very dark with this change. I don't think it was ever dark like that It's hard to see what the selected tool is. It's especially bad if you open the Visibility Filters popup, since the toggle button backgrounds now blend into the popup background so they no longer read as toggles. I think we need to restore the floating tool bar colors to what they were before.
* The contrast between the side panel and the main panel on the Welcome screen feels a bit too intense to me, compared to the other elements. I think the Welcome screen looked better before this change, but I concede the added contrast makes it more readable. Perhaps I just haven't acclimatized to the change yet. 🤔

2024-04-29 21:29 UTC, britzl commented
> * The section dividers in context menus straight up disappeared with this change. We need them back

I missed that!

<img width="188" alt="Screenshot 2024-04-29 at 23 28 38" src="https://github.com/defold/defold/assets/1300688/f8281eef-3b44-4373-bb32-af1d725ab443">

2024-04-29 21:56 UTC, britzl commented
> * The floating toolbar in scene views became very dark with this change

Good point. I issed that. Here's an update: 

<img width="233" alt="Screenshot 2024-04-29 at 23 55 20" src="https://github.com/defold/defold/assets/1300688/b3b474cd-d796-49bb-afb9-c7d9fede2e1b">

2024-04-29 22:08 UTC, britzl commented
> * There is more contrast in editable fields, due to the higher text intensity and darker field backgrounds. However, the field labels now appear to have slightly less contrast against the background. Combined with the higher contrast field values, the labels are further diminished against the background due to their proximity to a higher-contrast element. I'm not sure if I find the end result to be less or more readable. I'm torn if I think we should make this change.

Well, I went back to what we had in 2020 before we changed the styles. And in 2020 the field labels were slightly lower in contrast than the main field labels.

<img width="391" alt="fieldvalues_current" src="https://github.com/defold/defold/assets/1300688/ca3aa53c-d5dc-4e4b-aaa9-7fa4669a372e">

I like the lower contrast field values. They are only used as hints of what's supposed to go into each field, and as such I think they should have a lower contrast than the main value.

2024-04-30 05:40 UTC, britzl commented
> * I think we should make it consistent if we want to to make this change. I find the overall impression of editing a material slightly "messier" visually now.

How is it messier? It looks almost exactly the same. The difference is that the text in the input fields are brighter. Otherwise they're the same, no?

<img width="1510" alt="Screenshot 2024-04-30 at 07 38 45" src="https://github.com/defold/defold/assets/1300688/f3806a9f-3451-407d-bf63-c3114464e05c">

2024-04-30 05:43 UTC, britzl commented
> * The contrast between the side panel and the main panel on the Welcome screen feels a bit too intense to me, compared to the other elements. I think the Welcome screen looked better before this change, but I concede the added contrast makes it more readable. Perhaps I just haven't acclimatized to the change yet.

I don't have a super strong opinion on the Welcome Screen. Again, I went back to how it looked in 2020, before changes to the colors were made.

2024-04-30 08:42 UTC, matgis requested changes
You fixed the toolbar in the Scene View, but the Visibility Filters popup that appears when you click the eye icon is still dark.

2024-04-30 08:44 UTC, matgis commented
> How is it messier? It looks almost exactly the same. The difference is that the text in the input fields are brighter. Otherwise they're the same, no?

There are now three distinct intensities of controls, whereas before it was two. It doesn't matter. We can do a pass on it later.

2024-04-30 09:16 UTC, britzl commented
> You fixed the toolbar in the Scene View, but the Visibility Filters popup that appears when you click the eye icon is still dark.

Thanks. Fixed:

<img width="281" alt="Screenshot 2024-04-30 at 11 15 46" src="https://github.com/defold/defold/assets/1300688/322edf59-aa07-4fd7-b60a-68dd6747e871">

2024-04-30 09:19 UTC, matgis approved these changes
Go ahead and merge!

2024-04-30 09:25 UTC, britzl commented
> > How is it messier? It looks almost exactly the same. The difference is that the text in the input fields are brighter. Otherwise they're the same, no?
> 
> There are now three distinct intensities of controls, whereas before it was two. It doesn't matter. We can do a pass on it later.

True. I probably prefer what we have currently, but I didn't want to bring my own opinion into this change but rather revert to the original colours.

But I agree that we should make another pass over it at some point to perhaps increase contrast a bit more in some places, but also maybe tweak the cljfx form styling, which is a bit messy, especially when it comes to editable vs non editable fields and the table views.

2024-05-13 09:09 UTC, merged