Editor: Support viewing library resources in Custom Code Editor
defold/defold pull request #9144
Opened 2024-06-28 15:53 UTC by matgis

It is now possible to view library resources with the configured Custom Code Editor.

Fixes #4964

### Technical changes
* Added boolean argument to `fs/set-executable!` and `fs/set-writable!`.

2024-06-28 17:17 UTC, AGulev commented
Now it's impossible just open a code file in a lib. it opens as text:
https://github.com/defold/defold/assets/2209596/65a6933a-0a67-41cd-98ed-b9d173a86ef6

2024-06-28 17:22 UTC, matgis commented
This was also the case before this change. It opens like that because the resource is read-only inside the `.zip` file. I want to make it open in the proper code editor in some kind of read-only mode, but that is a separate issue.

2024-06-28 17:22 UTC, AGulev requested changes
Now it's impossible just open a code file in a lib. if no custom editor specified 
 it opens as text:

https://github.com/defold/defold/assets/2209596/864d470b-c2d8-4bdd-b4b3-7c21cc9be6fb

2024-06-28 17:24 UTC, AGulev commented
@matgis then it's new 1.9.1 regression. It was fine before 1.9.0:


https://github.com/defold/defold/assets/2209596/06cbbfda-f24a-49e9-8f3a-176ad030005e

2024-06-28 17:30 UTC, matgis commented
Huh. Good to know! It may have happened with the save-value changes. I'll have to look into it on Monday. I checked in `dev` a few commits prior to the recent **Open As** changes, and it does open the library files in the primitive text view before this PR.

2024-07-01 07:34 UTC, AGulev approved these changes

2024-07-01 07:35 UTC, merged