Material and compute script modules
defold/defold pull request #9208
Opened 2024-07-19 12:16 UTC by Jhonnyg

Two new script modules have been added to the engine,`material` and `compute`, that can be used to get and set constants, attributes and textures from material and compute resources.

2024-08-07 18:03 UTC, Jhonnyg commented on engine/gamesys/src/dmsdk/gamesys/resources/res_material.h
> +        dmhash_t            m_TextureResourcePaths[dmRender::RenderObject::MAX_TEXTURE_COUNT];
Used in the new functions for getting where the texture came from

2024-09-09 09:00 UTC, JCash requested changes
A doc issue.
Also a question if the set_vertex_attribute() could/should take more than one attribute at a time?

2026-05-02 16:51 UTC, Jhonnyg commented
@codex review pr

2026-05-18 11:15 UTC, JCash requested changes
overall good.
looks like an alignment issue when writing vertex data

2026-05-18 11:15 UTC, JCash commented on engine/gamesys/src/gamesys/gamesys_private.cpp
> +                *((float*) value_write_ptr) = value;
Due to alignment, I think sanitizer tools may complain if we do unaligned writes.
I think we use memcpy() elsewhere

2026-05-18 11:15 UTC, JCash commented on engine/gamesys/src/gamesys/gamesys_private.h
> +    void    VertexAttributeToFloats(const dmGraphics::VertexAttribute* attribute, const uint8_t* value_ptr, float* out);
Perhaps time to create an issue like "Move geometry related code into a geometry library" or something, so that we can move more code "centrally", away from the gamesys components.

2026-05-18 13:29 UTC, merged