Fix a copy error when importing the glTF file - it should copy the bone from `skin->m_Bones` to `sorted_bones` in the `SortSkinBones`.
defold/defold pull request #9673
Opened 2024-10-31 12:29 UTC by jixingcn

Fix a copy error when importing the glTF file - it should copy the bone from `skin->m_Bones` to `sorted_bones` in the `SortSkinBones`.

The editor failed to import the [RiggedFigure](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/RiggedFigure), 
Then I debugged it and found somebody with the same problem in the forum.

2024-11-22 12:13 UTC, jixingcn commented
Excuse me @britzl
How to push this issue forward?

2024-11-22 12:30 UTC, JCash requested changes
Please

(update)
Not sure why this post only says "please", I'm sure I wrote something more descriptive 🤔 
In any case, the below comments are up-to-date and my current concern.

2024-11-23 05:39 UTC, jixingcn commented on engine/modelc/src/modelimporter_gltf.cpp
> +            CopyBone(&skin->m_Bones[i], &sorted_bones[new_index]);
Here, we need to store the skin bones and the sorted bones temporarily. The following line `skin->m_Bones.Swap(sorted_bones);` swap the sorted bones back to the skin bones.

I don't think it needs a unit test.

2024-11-23 05:41 UTC, jixingcn commented on engine/modelc/src/modelimporter_gltf.cpp
> +            CopyBone(&skin->m_Bones[i], &sorted_bones[new_index]);
Here, we need to store the skin bones and the sorted bones temporarily. The following line `skin->m_Bones.Swap(sorted_bones);` swap the sorted bones back to the skin bones.

I don't think it needs a unit test.

2024-11-23 05:47 UTC, jixingcn commented on engine/modelc/src/modelimporter_gltf.cpp
> +            CopyBone(&skin->m_Bones[i], &sorted_bones[new_index]);
We can see that the `sorted_bones` never stores any data before. All skin bones will be reset by this line.

2024-11-23 05:54 UTC, jixingcn commented on engine/modelc/src/modelimporter_gltf.cpp
> +            CopyBone(&skin->m_Bones[i], &sorted_bones[new_index]);
I found this when I tried some glTF files that come from the [https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models).

2024-12-04 09:08 UTC, JCash commented on engine/modelc/src/modelimporter_gltf.cpp
> +            CopyBone(&skin->m_Bones[i], &sorted_bones[new_index]);
I think since this code path is getting tested more, and if you found an issue, it's worth testing.
Find the failing model, and add it to the test.

2024-12-07 11:28 UTC, jixingcn commented on engine/modelc/src/modelimporter_gltf.cpp
> +            CopyBone(&skin->m_Bones[i], &sorted_bones[new_index]);
OK. I will submit the failing model.

2024-12-07 13:18 UTC, jixingcn commented on engine/modelc/src/modelimporter_gltf.cpp
> +            CopyBone(&skin->m_Bones[i], &sorted_bones[new_index]);
The issue model is [https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/CesiumMan/glTF-Binary](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/CesiumMan/glTF-Binary).

**Yep, I found it is no issue when importing the Defold editor(1.9.3). But it has a problem when I debug it by `test_model.exe`.**

**The issue only happens when `// do the remapping, i.e. flattern the hierarchy`.**

Before `CopyBone(&sorted_bones[new_index], &skin->m_Bones[i]);`, the `skin->m_Bones` still stored all bones data:
![image](https://github.com/user-attachments/assets/34964b44-7f5b-4c75-bcb3-1c07ef40fb77)

And then, `skin->m_Bones` and `sorted_bones` are lost all bones data:
![image](https://github.com/user-attachments/assets/cc90e824-b1b4-4a6c-a02f-89ed2979734f)

2024-12-07 13:26 UTC, jixingcn commented on engine/modelc/src/modelimporter_gltf.cpp
> +            CopyBone(&skin->m_Bones[i], &sorted_bones[new_index]);
Below is my fixed result:

![image](https://github.com/user-attachments/assets/d3652478-b002-4fb9-bf2b-d997156fd40c)

After `skin->m_Bones.Swap(sorted_bones);`, all bones data were remapped.
![image](https://github.com/user-attachments/assets/cb832d29-5c96-4c95-bc9d-e8fd2c41058e)

2024-12-07 13:29 UTC, jixingcn commented on engine/modelc/src/modelimporter_gltf.cpp
> +            CopyBone(&skin->m_Bones[i], &sorted_bones[new_index]);
I will continue to check this problem.

2025-03-17 14:03 UTC, JCash commented
I recently did an update to our model loading, making sure we can load all the test models from Khronos.
During that process, I fixed a lot of smaller issues, and I think this one may have been fixed as well.
It would be great if you could reverify your issue to see if it's still there.
Thanks!

2025-05-14 15:24 UTC, JCash commented
Closing as no further feedback was added.

2025-05-14 15:24 UTC, closed without merging