Add ASTC texture compressor
defold/defold pull request #9883
Opened 2024-12-04 15:25 UTC by Jhonnyg

2024-12-04 15:26 UTC, Jhonnyg commented on editor/src/clj/editor/protobuf_forms.clj
> +    :texture-format-rgba-astc-12x12})
This means that the formats will NOT be shown in the editor, just so people don't start using them prematurely.

2024-12-04 15:28 UTC, Jhonnyg commented on engine/graphics/src/dmsdk/graphics/graphics.h
> +
UGH, we should really merge these formats with the proto file.. :')

2024-12-04 15:28 UTC, Jhonnyg commented on engine/graphics/src/opengl/graphics_opengl.cpp
> -        m_RenderDocSupport        = params.m_RenderDocSupport;
Not used in opengl any longer

2024-12-04 15:28 UTC, Jhonnyg commented on engine/graphics/src/opengl/graphics_opengl.cpp
> +            context->m_ASTCSupport = 1;
No need to set specific formats here, they should all be supported if we have any of the extensions.

2024-12-09 09:04 UTC, JCash requested changes
Looks good.
However, a small bpp issue left I believe

2024-12-09 09:04 UTC, JCash commented on engine/texc/src/test/test_texc.cpp
> +    ASSERT_TRUE(dmTexc::ASTCEncode(&settings, &out, &out_size));
Perhaps also check that the out size is <some_limit ?

2024-12-09 22:56 UTC, Jhonnyg commented on engine/graphics/src/vulkan/graphics_vulkan.cpp
> +            tex_data_size = tex_bpp * params.m_Width * params.m_Height * tex_layer_count;
Hmm, we might want to add a function that takes a width, height, format and slice count and gives a byte size back or something. Some formats are still 2 bits wide, so we need to account for that.

2024-12-10 12:32 UTC, merged