Added API to get AABB for models.
defold/defold pull request #9946
Opened 2024-12-17 23:15 UTC by ekharkunov

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

2024-12-18 06:59 UTC, aglitchman commented
It's simply a gift! 🤩 Thank you!

2024-12-18 08:47 UTC, ekharkunov commented
> It's simply a gift! 🤩 Thank you!

Did you try it?

2024-12-19 09:44 UTC, ekharkunov commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +        {"play",    LuaModelComp_Play}, // Deprecated
Formatting.

2024-12-19 09:45 UTC, ekharkunov commented on engine/gamesys/src/gamesys/test/create_prebuilts.sh
> +# Make sure you have $DYNAMO_HOME setup and built bob.jar, then run:
Use bob.jar because of `builtins` needs. (Not worked for me with bob-light).

2024-12-19 09:45 UTC, ekharkunov commented on engine/gamesys/src/gamesys/test/create_prebuilts.sh
> +cp build/default/model/aabb_model.modelc ../model/aabb_model.prebuilt_modelc
New prebuilt content for model tests.

2025-01-07 14:41 UTC, JCash requested changes

2025-01-07 15:40 UTC, britzl commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +     * ```
I agree with this! But maybe the returned table shouldn't be keyed on mesh id and instead be an array? In the case when requesting a single aabb it will be a bit easier to get the min and max

```lua
local aabb = model.get_aabb("#model")
pprint(aabb) -- { [1] = { id = hash("Sword"), min = vmath.vector3(-0.5, -0.5, 0), max = vmath.vector3(0.5, 0.5, 0) }, [2] = { id = hash("Shield"), min = vmath.vector3(-0.5, -0.5, -0.5), max = vmath.vector3(0.5, 0.5, 0.5) } }

local aabb = model.get_aabb("#model", "Sword")
pprint(aabb) -- { [1] = { id = hash("Sword"), min = vmath.vector3(-0.5, -0.5, 0), max = vmath.vector3(0.5, 0.5, 0) } }
print(aabb[1].min, aabb[1].max)
```

2025-01-07 15:43 UTC, britzl commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +        {"play",    LuaModelComp_Play}, // Deprecated
BTW, We should add this to our list of deprecations to remove in our big breaking change release.

2025-04-07 14:59 UTC, ekharkunov commented on engine/gamesys/src/gamesys/test/create_prebuilts.sh
> +# Make sure you have $DYNAMO_HOME setup and built bob.jar, then run:
I've added empty assets for display profiles, gamepad mappings, etc. and not it can be built with bob-light.jar

2025-04-07 14:59 UTC, ekharkunov commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +     * ```
I decided to remove 2nd argument and always return all information in form of `<hashed_mesh_id> = <aabb_info>`.

2025-04-07 14:59 UTC, ekharkunov commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +     * @param mesh_id [type:string|hash|url|nil] the id of the mesh (optional)
2nd argument was removed

2025-04-07 15:30 UTC, ekharkunov commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +        {"play",    LuaModelComp_Play}, // Deprecated
https://github.com/defold/defold/issues/10455
Mentioned it here

2025-04-08 07:17 UTC, britzl commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +     * Get AABB of the meshes. If `mesh_id` would be passed as a second argument - return AABB only for that mesh.
This still mentions `mesh_id` as the second argument

2025-04-08 07:39 UTC, britzl approved these changes, later dismissed

2025-04-08 07:51 UTC, JCash submitted a review, later dismissed
As discussed, needs a rename of the api function

2025-04-08 07:51 UTC, JCash commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +        lua_newtable(L);
If you know the count (line below), you can create the table with `lua_createtable(L, 0, n)`
https://www.lua.org/manual/5.1/manual.html#lua_createtable

2025-04-08 07:51 UTC, JCash commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +        return 1;
I don't recall the design on this, but what if I wanted the AABB for the _model_, and not each individual mesh?

2025-04-08 20:05 UTC, ekharkunov commented on engine/gamesys/src/gamesys/scripts/script_model.cpp
> +        return 1;
Added `model.get_aabb()` for AABB of the whole model. Mesh's AABB can be retrieved via `model.get_mesh_aabb()`

2025-04-09 07:17 UTC, britzl approved these changes

2025-04-09 13:25 UTC, JCash approved these changes
lgtm

2025-04-09 13:34 UTC, merged