Append raw texture data after protobuf header
defold/defold pull request #9950
Opened 2024-12-18 10:35 UTC by Jhonnyg

2025-01-07 08:43 UTC, Jhonnyg commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/TextureGenerator.java
> -                }
Name was always passed as null to the function

2025-01-07 08:47 UTC, Jhonnyg commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TextureUtil.java
> +    private static int getTextureGenerateResultByteIndex(TextureImage textureImage, int alternative, int mipMap) throws TextureGeneratorException {
This can probably be written differently, but I didn't understand the old code so I opted for the simplest solution.

2025-01-07 08:51 UTC, Jhonnyg commented on editor/project.clj
> +                                                    "-Ddefold.extension.texturepacker.url=https://github.com/defold/extension-texturepacker/archive/refs/heads/update-to-new-texture-format.zip"
When this has been approved, I will merge TP extension PR and use the new release.

2025-01-07 09:01 UTC, Jhonnyg commented on editor/test/resources/save_data_project/checked.tpinfo
> +    }
We were using an old TP extension, the new one has pivots so it's included now

2025-01-07 09:36 UTC, JCash approved these changes, later dismissed
lgtm

2025-01-07 09:36 UTC, JCash commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TextureUtil.java
> +    private static int getTextureGenerateResultByteIndex(TextureImage textureImage, int alternative, int mipMap) throws TextureGeneratorException {
Yeah, I want the "alternatives" to be removed.
It's not the way we want to provide alternative texture packs imo.

2025-01-07 09:36 UTC, JCash commented on engine/graphics/proto/graphics/graphics_ddf.proto
> +        optional uint32 data_size                 = 11;
What does this represent? isn't it either `mip_map_size` or `mip_map_size_compressed`, depending on the `compression_type`?

Perhaps add a comment in the file?

2025-01-07 09:40 UTC, AGulev submitted a review, later dismissed
👍

2025-01-10 10:58 UTC, matgis requested changes
Looks like cube map code paths need to be updated in the editor. I'm also concerned about peak memory usage during project builds increasing after this change.

2025-01-10 10:58 UTC, matgis commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TextureUtil.java
> +    private static int getTextureGenerateResultByteIndex(TextureImage textureImage, int alternative, int mipMap) throws TextureGeneratorException {
The method name is a bit confusing. `ByteIndex` sounds like it refers to an offset in a continuous array of bytes, but it is really the index of one of the byte arrays inside the `GenerateResult.imageDatas`.

2025-01-10 10:58 UTC, matgis commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TextureUtil.java
> +                    ArrayList<byte[]> textureBytes = generateResults[k].imageDatas;
Consider renaming to `imageDatas` or `mipImageByteArrays` for clarity?

2025-01-10 10:58 UTC, matgis commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TextureUtil.java
> +                    int byteIndex = getTextureGenerateResultByteIndex(generateResults[k].textureImage, i, j);
`mipImageIndex`?

2025-01-10 10:58 UTC, matgis commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TextureUtil.java
> +    public static byte[] generateResultToByteArray(TextureGenerator.GenerateResult generateResult) {
The method name is a bit confusing to me.

What exactly is in this `ByteArray` that this method returns? It seems to return the bytes we should write to a `.texturec` resource when building?

Maybe we could name it `generateResultToTextureResourceBytes` or something like that?

Although to be honest, I would prefer a `writeTextureResource(OutputStream)` method on `GenerateResult` that writes it to an `OutputStream` instead of returning a concatenated byte array like this one does. Then the editor could be changed to write the `GenerateResult` directly to an output `.texturec` file without having to allocate the concatenated byte array. And you could implement this helper method by calling that with a `ByteArrayOutputStream`. If you know the output byte size, you can specify the capacity of the `ByteArrayOutputStream` when constructing it and avoid intermediate allocations during the write, so it might be helpful to have a `calculateTextureResourceSize()` method on `GenerateResult` as well for this purpose.

2025-01-10 10:58 UTC, matgis commented on editor/src/clj/editor/pipeline/tex_gen.clj
> +    (TextureUtil/createCombinedTextureImage (into-array texture-generator-results) texture-type)))
`TextureUtil/createCombinedTextureImage` is called in the `assemble-cubemap-texture-images` function below as well, so you need to update that to return a `TextureGenerator$GenerateResult` and all callers of that too.

2025-01-10 10:58 UTC, matgis commented on editor/src/clj/editor/image.clj
> +            texture-protobuf-bytes (TextureUtil/generateResultToByteArray texture-generator-result)]
It's not really a `texture-protobuf` anymore, right? Maybe `texture-resource-bytes` or `texturec-bytes`?

2025-01-10 10:58 UTC, matgis commented on editor/test/integration/extension_texturepacker_test.clj
> +              built-texture (->> built-textureset :texture (workspace/build-path workspace) fs/read-bytes TextureUtil/byteArrayToTextureImage (protobuf/bytes->map-with-defaults Graphics$TextureImage)
We can use `protobuf/pb->map-with-defaults` here if we change `TextureUtil/byteArrayToTextureImage` to return a `TextureImage` instead of a byte array.

2025-01-10 11:48 UTC, Jhonnyg commented on editor/test/editor/pipeline/tex_gen_test.clj
> +        ^TextureGenerator$GenerateResult
It really isn't clear to me when and why I should add type hints, it _feels_ completely arbitrary sometimes when it makes sense.

2025-01-10 12:49 UTC, Jhonnyg commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TextureUtil.java
> +        }
I don't know for certain, but if I can make the change as you suggested it is better than before since we used to copy mipmap data into sequential byte strings for each textureimage. But if we can stream out the byte data it should be better than before.

2025-01-10 14:34 UTC, matgis commented on editor/test/editor/pipeline/tex_gen_test.clj
> +        ^TextureGenerator$GenerateResult
Yeah, it is a bit of a blemish on the language. There are basically three reasons why you might want to add a type hint.

The most important reason is to get rid of Reflection Warnings. When a particular named Java method has multiple overloads that vary only by argument type, applying a type hint can help it pick the correct one at compile time. If the argument types cannot be inferred, the compiler will output a Reflection Warning when you reload the file in the REPL, or print it to stdout when you run the program. These warnings should be taken seriously, since it means the call will use reflection to find the correct method implementation based on the types at runtime instead of compile time, which can make the call around 50 times slower.

The second reason to type hint is it to avoid boxed math. The JVM has primitive types like `long` and `double`, but all of its collection classes are designed to accept any value that is a `java.lang.Object`. So your `ArrayList<int>` is actually an `ArrayList<Object>` that stores a bunch of boxed `ints` as `java.lang.Integer` objects. In Java, you would get a value from such a collection and assign it to an `int num = arrayList.get(0))`, which would put an `int` on the stack and allow you to do efficient math with it and other primitive numbers. However, in Clojure vars aren't typed by default - everything is of type `java.lang.Object`. That is, unless you add a primitive type hint in the let binding like `(let [^int num (nth list 0)] ...)`. You can also type hint function arguments and return values as `^long` or `^double` to enable something similar to a `fastcall` (but only when a function has four or fewer arguments). You can turn on a compiler warning for boxed math by setting `(set! *unchecked-math* :warn-on-boxed)` at the top of your file. We do this in a bunch of places, but not everywhere since it can be a bit fiddly to solve completely. But it is probably worth addressing in places where we're doing a lot of math.

Finally, type hints are sometimes used for documentation purposes on function arguments and return values that are Java types. It might be nice to see that an argument is expected to be a `^String name`, for example.

The second question is where to put them. I prefer to use type hints on the function arguments, and always type hint the return value of any function that returns a Java type. If I add them in `let` bindings it is either because I want to put a primitive on the stack, or because a function or method I call does not have the correct return type declared. If it is our function, I add a return type hint to the function if possible (because that will benefit every call), but sometimes I need to put the hint at the call site instead. An example of that is stuff like the `nth` function. It has no way of knowing the type of the object it obtains from a collection, but maybe I know that I have a homogenous collection of objects of a particular type.

2025-01-15 10:04 UTC, Jhonnyg commented on editor/test/editor/pipeline/tex_gen_test.clj
> +        bytes   (TextureUtil/byteArrayToTextureImage protobuf-bytes)
right, yes that's true!

2025-01-16 09:32 UTC, matgis requested changes
Awesome work! ❤️

I would like to change the name of the `:build-fn` entry in the `artifact` to `:write-content-fn`, so it doesn't get confused with the existing `:build-fn` in the `build-targets`. Also, we might need to flush the `digest-output-stream` before getting the `sha1` from it. Not entirely sure.

2025-01-16 09:32 UTC, matgis commented on editor/src/clj/editor/pipeline/tex_gen.clj
> +    (digest/completed-stream->hex digest-output-stream)))
Do we need to flush the stream before calling `completed-stream->hex` here? 🤔

If `writeGenerateResultToOutputStream` flushes it internally, we should probably add a comment here.

2025-01-16 09:32 UTC, matgis commented on editor/src/clj/editor/pipeline.clj
> +  (assert (or (some? (:build-fn artifact)) (some? (:content artifact))))
I love this change!

Although I'm not entirely happy about calling this `:build-fn`, since we also have `:build-fn` in the `build-targets` that means something else entirely.

Maybe something like `:write-content-fn` would be better?

2025-01-16 09:32 UTC, matgis commented on editor/src/clj/editor/pipeline/tex_gen.clj
> +(defn build-texture-resource-fn [resource user-data]
Rename to `write-texturec-content-fn`?

2025-01-16 14:22 UTC, matgis approved these changes, later dismissed
Editor changes look good!

2025-01-16 15:13 UTC, merged