GL ES for the Linux ARM64 target to support running on Raspberry Pi and Linux handhelds
defold/defold pull request #9984
Opened 2024-12-29 21:32 UTC by aglitchman

This PR changes the used graphics API from desktop OpenGL to OpenGL ES for Linux ARM64 platform. Devices on this platform usually do not have support for desktop OpenGL because they are built on mobile chips. Also added mapping gamepad for Linux handhelds to the gamepads database.

Fixes #9826

### Technical changes
* I rebuilt the GLFW package for arm64 linux for the reason that the previous version required libGL.so, which is not present on the target system. It was built using clang 16 and the build script was improved accordingly.

2024-12-29 21:36 UTC, aglitchman commented on engine/platform/src/platform_window_glfw3.cpp
> +        glfwSetErrorCallback(OnError);
I moved the error callback setup here, since it can be done before `glfwInit`, according to the documentation.

2025-01-13 13:47 UTC, JCash requested changes
While it might work as it is right now, I do wonder if we want to lock down into opengles/handhelds only.

I think my suggested changes gets us 90% of the way to a more modular approach (like we usually do when selecting backends)

Only piece missing is how to change the shader language+version properly.

While I mark this for "change requested", it's also not set in stone, I wanted to mark it as "not done with decisions yet" so we can discuss it further :)

2025-01-13 13:47 UTC, JCash commented on build_tools/waf_dynamo.py
> +        conf.env['LIB_OPENGL'] = ['EGL', 'GLESv1_CM', 'GLESv2']
My main concern is if there will be an actual "desktop" target using this.
For better support in the future, I think the these options should be chosen using an app manifest approach (i.e. choosing the graphics backend: opengl, gles, webgpu etc).

Question is, can we go a head with this, and not make it breaking change if we want to support arm64-linux desktop targets?
I wonder if it's not better to default to OpenGL, and leave the custom backend selection for the app manifest.
(we've also wanted to move to Vulkan as default which just highlights the point)

2025-01-13 13:47 UTC, JCash commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilers.java
> +                } break;
I think this is a bit too limiting.
Using this approach we cannot switch from gles to glsl.

I think we need another way of selecting the shader language. @Jhonnyg do you have any thoughts around this?

2025-01-13 13:47 UTC, JCash commented on engine/graphics/src/opengl/graphics_opengl.cpp
> +    // NOP
If it's not needed, please remove the dead code.

2025-01-13 13:47 UTC, JCash commented on engine/graphics/src/opengl/graphics_opengl.cpp
> +#if defined(__EMSCRIPTEN__) || defined(__ANDROID__) || (defined(__linux__) && defined(__aarch64__))
These switches start to get complicated.
I propose moving this switch to the `wscript`, and adding a `DM_GRAPHICS_USE_OPENGL`/`DM_GRAPHICS_USE_OPENGLES` respectively.

2025-01-13 13:47 UTC, JCash commented on engine/gamesys/wscript
> +        conf.env['LIB_X'] = ['Xext', 'X11', 'Xi', 'EGL', 'GLESv1_CM', 'GLESv2']
Ok for tests, and I know it's old code, but the build artefact should probably use `use = "X OPENGL"` and set those libraries into the LIB_OPENGL variable instead (as you did in the wscript above)

2025-01-13 13:47 UTC, JCash commented on engine/graphics/src/opengl/graphics_opengl.cpp
>  #endif
Since we are talking about a target that may want to see both OpenGL and OpenGLES, I think there needs to be some design decisions:
* Should we only support OpenGLES?
* How to select between the targets? Compile time or runtime?

We could for instance easily compile two versions of this file (graphics_opengl.cpp` into two libraries `libgraphics_opengl.a` and `libgraphics_opengles.a`, only difference is using different defines (USE_OPENGLES).

Or, do we want to be able to check at runtime?
(I'm not even sure it's even possible, given that they use different headers+libraries)
And it also requires the built project to include two versions of the same shaders, which might not be what one wants.

My gut feeling is that the two-library-approach is the easier route to take.

2025-01-13 13:47 UTC, JCash commented on engine/platform/src/platform_window_glfw3.cpp
> +        }
Is this a fix for something else?
It doesn't seem like it's arm64 related?

2025-01-13 13:47 UTC, JCash commented on engine/platform/src/platform_window_glfw3.cpp
> +        glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
Not knowing what the different targets support, but I would think it's not unreasonable to think one of them might support opengles 3?

E.g. the android code does this to detect it:
```
        const char* version = (char *) glGetString(GL_VERSION);
        if (strstr(version, "OpenGL ES 2.") != 0) {
            context->m_IsGles3Version = 0;
        } else {
            context->m_IsGles3Version = 1;
        }
```

Also, I'd expect the gles variables to be set accordingly:
```
context->m_IsGles3Version = ...;
context->m_IsShaderLanguageGles = ...;
```

2025-01-15 17:01 UTC, Jhonnyg commented on com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilers.java
> +                } break;
Hmm hm, yes I think we need a different approach to this. I kinda feel like you should be able to configure your project to build with both ES and desktop OpenGL support + configure which shader versions to include. If for example you don't care about ES2/WebGL1 you shouldn't be forced to include them. As it stands right now, I don't have a solution for this, we need to design that setup a bit.

2025-01-15 17:02 UTC, Jhonnyg commented on engine/graphics/src/opengl/graphics_opengl.cpp
> +#if defined(__EMSCRIPTEN__) || defined(__ANDROID__) || (defined(__linux__) && defined(__aarch64__))
Agreed.

2025-01-15 17:10 UTC, Jhonnyg commented on engine/graphics/src/opengl/graphics_opengl.cpp
>  #endif
I think you can technically link both desktop and ES into the same binary and then load the correct symbols depending on which of the libraries you use. I think there's loaders like GLAD or GLEW that we could use instead of our current setup, but I'd like to take the shortest path for this as possible. And that likely means building two libraries that use different headers and libraries.

2025-01-15 22:01 UTC, aglitchman commented
> While it might work as it is right now, I do wonder if we want to lock down into opengles/handhelds only.

> Question is, can we go a head with this, and not make it breaking change if we want to support arm64-linux desktop targets?
> I wonder if it's not better to default to OpenGL, and leave the custom backend selection for the app manifest.
(we've also wanted to move to Vulkan as default which just highlights the point)

I want to discuss this, because I think the decision will make the work more complicated 🙌

I think the Arm64 Linux platform should be kept simple in support, i.e. only GL ES, and for more advanced users let it be Vulkan (which is not there yet, but it's easy to add in the next phase).

Arguments for:
- Arm64 were originally mobile chips and they didn't have desktop OpenGL ([mentioned in the original issue](https://github.com/defold/defold/issues/9826)). At most they got Vulkan and DirectX because of Windows Phone and Windows ARM. And Apple added it for backward compatibility (100% through some layer on Metal).
- Google search tells me that desktop OpenGL on current modern devices is only on: NVIDIA's Jetson and Asahi Linux for the M1/M2. Which have GL ES and Vulkan, too. Why then do these platforms need desktop OpenGL from Defold?
- By supporting Desktop OpenGL and GL ES we will x2 complicate support of this platform. For example, I don't have an arm64 linux device with desktop GL and I won't be able to test it in real life at all.
- OpenGL desktop has been dead for 7 years.

To sum up, I believe that Arm64 Linux platform will have an audience of few Defold users, including me. And I'm sure that hardly anyone here will need desktop OpenGL. And if it is left on by default instead of GL ES, I'm sure that the first question will be: “I built an arm64 linux version, tried to run it on my RPi, but the game doesn't run because there is no libGL.so library. what should I do?”.

2025-01-20 10:49 UTC, JCash commented
> I think the Arm64 Linux platform should be kept simple in support

Agreed.
I would however wish to see a `libgraphics_opengles.a` library, with a `GraphicsAdapterOpenGLES`.
Granted, Android doesn't have it, but I think that's a bug imho, as we know GL/GLES work differently.
A lot of our architecture revolve around switching out libraries, and as such, I'd like to make sure the libraries do what they promise. (e.g. "libgraphics_opengl.a" is _not_ an opengles library)

We can still use the new "libgraphics_opengles.a" as the default library, and have a "libgraphics_opengl.a" later on (if someone wants it).

So, to facilitate this, we should build the "graphics_opengl.cpp" into two different versions:
* `libgraphics_opengl.a` - using `#DM_GRAPHICS_USE_OPENGL`
* `libgraphics_opengles.a` - using `#DM_GRAPHICS_USE_OPENGLES`

The waf_dynamo.py should also define the library using `LIB_OPENGLES` just like we do with `LIB_OPENGL`
And the vanilla engine would then use the `GraphicsAdapterOpenGLES` and `OPENGLES` when building arm64-linux.

And, in the shader compiler, we'll still have to hardcode the gles shader, as we can currently only detect `GraphicsAdapterXXX` symbols from the app manifest.

2025-01-20 20:29 UTC, aglitchman commented
> I would however wish to see a `libgraphics_opengles.a` library, with a `GraphicsAdapterOpenGLES`.
> Granted, Android uses `libgraphics_opengl.a), but I consider that a bug imho.

Now it's clear! 🙌 Many thanks. I'll update the PR as advised.

2025-01-28 10:20 UTC, yaing11 commented
@aglitchman Many thanks for your work. It's a great job. I've been waiting for a long time this PR. 

I have two questions.
1. Please tell me, will it work on the **wayland** linux-devices with arm64 ?
2. Do you have success in the building defold game on the RPI ?

2025-01-28 10:24 UTC, aglitchman commented
> @aglitchman Many thanks for your work. It's a great job. I've been waiting for a long time this PR.
> 
> I have two questions.
> 
> 1. Please tell me, will it work on the **wayland** linux-devices with arm64 ?
> 2. Do you have success in the building defold game on the RPI ?

🙌🏻

1. Yes
2. I didn't test, but it should run well.

I'll finish the work on the changes this week.

2025-02-03 23:54 UTC, aglitchman commented
Not ready for a review yet - I think I've not finished something yet (I'll look tomorrow).

2025-02-04 14:03 UTC, aglitchman reviewed
Summary of changes:
1) Added a split into `GraphicsAdapterOpenGL` and `GraphicsAdapterOpenGLES` adapters for desktop GL and GL ES, using a single source code based on the definition `DM_GRAPHICS_USE_OPENGLES`. For arm64 linux only, so as not to break all other platforms. And for the reason that a full refactoring of GL/GLES into two adapters for all platforms has to be done in a separate PR and by someone from the team, since you need experience and access to CI (i.e. I as a 3rd party contributor without your CI can't even check the correctness of what I'll do).
2) Bob for arm64 linux builds shaders for GL ES, without desktop GL, as right now there will only be a GL ES adapter. I think that's ok.
3) Platform code GLFW3 chooses the proper initialisation path by graphics adapter type.

Only one thing: I didn't find where I should add new definitions for `GraphicsAdapterOpenGLES` for extender and for forming appmanifest from editor.

2025-02-10 09:10 UTC, JCash approved these changes, later dismissed
Lgtm!
Well done!

2025-02-10 09:10 UTC, JCash commented on engine/graphics/src/opengl/graphics_opengl_defines.h
> +#if defined(__aarch64__)
Hmm, I don't think this header is included from dmSDK?
Do you have a link to that?

2025-02-10 09:10 UTC, JCash commented on engine/tools/wscript
> +        conf.env['LIB_X'] = ['Xext', 'X11', 'Xi', 'EGL', 'GLESv1_CM', 'GLESv2']
(old code, I know)
The "X" library shouldn't need these extra GL libraries.
Instead, they should go into "LIB_OPENGLES" (although that is also already setup in waf_dynamo.py)
Our wscripts have tons of small issues like that.

2025-02-10 09:42 UTC, Jhonnyg submitted a review, later dismissed
LGTM! Well done 👏

2025-02-15 10:43 UTC, yaing11 commented
@aglitchman Hello sir. Great job.  Please tell me, when I can to try to build defold for my linux/arm64 device.
Many thanks in advice.

2025-02-16 15:23 UTC, aglitchman commented on engine/graphics/src/opengl/graphics_opengl_defines.h
> +#if defined(__aarch64__)
My fault! Changed to `DM_GRAPHICS_USE_OPENGLES`. Thanks!

2025-02-16 15:41 UTC, aglitchman commented on engine/tools/wscript
> +        conf.env['LIB_X'] = ['Xext', 'X11', 'Xi', 'EGL', 'GLESv1_CM', 'GLESv2']
I apologise - I overlooked this change. As with other wscripts, `LIB_X` is no longer needed for Linux, so I removed it for both platforms. And as I understand it, if the engine builds with all the tests after these deletions, then it's ok.

2025-02-16 15:44 UTC, aglitchman commented
Finalised the changes taking into account the last two comments from @JCash.

( I'm completely brain-dead from the Github PR interface and I think I'm hitting the wrong buttons - I'll go study their documentation).

2025-02-19 08:28 UTC, Jhonnyg commented
@aglitchman if you could fix the conflict we are ready to merge this pr!

2025-02-19 12:18 UTC, aglitchman commented
> @aglitchman if you could fix the conflict we are ready to merge this pr!

Give me a couple of hours - I'll merge and check on the device if the gamepad mapping needs to be changed that was written before your fix.

2025-02-19 13:09 UTC, aglitchman commented
Done! It can be merged now.

2025-02-21 13:20 UTC, Jhonnyg approved these changes

2025-02-21 13:21 UTC, merged